Do not create php cluster zip

diff --git a/nbbuild/hudson/trunk b/nbbuild/hudson/trunk
--- a/nbbuild/hudson/trunk
+++ b/nbbuild/hudson/trunk
@@ -11,28 +11,17 @@ then
     fi
     dir=`dirname $0`/../..
     cd $dir
-elif [ `ant -f nbbuild/build.xml print-cvs-modules | perl -ne 'print sort qw(jemmy jellytools testtools xtest), split /[, ]/, $1 if /cvsmodules=\[(.+)\]/'` \!= `perl -e 'opendir D, "."; print sort grep {!/\.\.?/ && -d} readdir D; closedir D'` ]
-then
-    echo "Set of modules changed, getting fresh checkout..."
-    rm -rf `ls | fgrep -v nbbuild`
-    ant -f nbbuild/build.xml checkout cvs-clean || exit
-elif [ builds/`ls -1 ../builds | tail -2 | head -1` '!=' `readlink ../lastSuccessful` ] || fgrep -q StackTrace ../lastSuccessful/junitResult.xml
-then
-    echo "Previous build failed, running clean build this time..."
-    ant -f nbbuild/build.xml cvs-clean || exit
+else
+#    echo "Previous build failed, running clean build this time..."
+    ant -f nbbuild/build.xml hg-clean || exit
 fi
-
-for www in */www ; do
-    if [ \! -f $www/.IGNOREME ] ; then
-        rm -rf $www
-        cp -r nbbuild/dummy $www
-    fi
-done
 
 DIST=$PWD/nbbuild/dist
 rm -rf $DIST/
 
-# YYYYMMDDhhmmss timestamp corresponding to cvs tag
+# XXX should use hg id as the build number; timestamp is useless!
+
+# YYYYMMDDhhmmss timestamp
 BUILDNUMBER=`echo $BUILD_ID | tr -d _-` 
 BUILDNUM=$BUILD_TAG
 
@@ -62,7 +51,7 @@ find netbeans | egrep -v "netbeans/(extra|testtools|xml|java|apisupport|harness|
 
 cd netbeans
 expat='extra|testtools'
-for c in platform ide java apisupport harness enterprise profiler uml visualweb ruby mobility soa xml cnd identity php; do
+for c in platform ide java apisupport harness enterprise profiler uml visualweb ruby mobility soa xml cnd identity; do
     find * | egrep "^$c[0-9]*/" | zip -q $DIST/zip/moduleclusters/$BASENAME-$c.zip -@ || exit
     expat="$expat|$c[0-9]*"
 done
